### ISSUE TITLE
Please delete the private information in your fork

### ISSUE THREAD

**Issue by Diaob** [janstk/tutorialspointCppBook#1]
I found you fork my fork,but you didn't delete my information in time.
Now that the project is under your control,<h3>please delete my information remained in your fork.</h3>
Your fork address:https://github.com/janstk/z_ShadowVPN
And my information remained in the <h4>readme.md</h4>
(including my e-mail address and some bad words)
Thank you,and I hope you will delete as soon as you can.
Best Wishs.

**Comment by janstk** [comment]
sorry ~ i'll delete later
